CREATE TABLE Student (
    StudentID INT PRIMARY KEY,
    StudentName VARCHAR(20) NOT NULL UNIQUE,
    DOB DATE NOT NULL,
    Gender VARCHAR(10) NOT NULL,
    DepartmentID INT NOT NULL
);
DESC STUDENT;
INSERT STUDENT VALUES("1001","AATHIRAJ","2007/05/17","MALE","101");
DESC STUDENT;
SELECT*FROM STUDENT;
